### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by bengalspice** [pgreischar/intro-data-capstone-biodiversity#6]
Overall, Good Job!

If you decide to play around the project more, I suggest playing around with the data and seeing if you discover anything new from comparing other species. Also, it might be fun to play around with customizing the graph visualization to be more appealing. Also, try graphing the data using line graphs or pie charts to see if the data is easier to understanding visually.

**Comment by pgreischar** [comment]
I agree.  I didn't really expand out beyond the basic instructions.   I wasn't sure the extent to which that was appropriate.    I agree that the visualizations and .ppt file could be more appealing.
